<?php
/**
 * @OA\Schema(
 *     schema="inicioSesion",
 *     description="Datos Usuario.",
 *     required={
 *      "username",
 *      "password" 
 *     },
 *     @OA\Property(
 *       property="usuario",
 *       type="array",
 *       description="Array datos usuario.",
 *       @OA\Items(
 *          @OA\Property(
 *             property="id_usuario",
 *             type="integer",
 *          ),
 *          @OA\Property(
 *             property="usuario",
 *             type="string",
 *          ),
 *          @OA\Property(
 *             property="nombres",
 *             type="string",
 *          ),
 *          @OA\Property(
 *             property="apellidos",
 *             type="string",
 *          ),
 *          @OA\Property(
 *             property="estado",
 *             type="boolean",
 *          ),
 *          @OA\Property(
 *             property="fecha_nacimiento",
 *             type="integer",
 *          ),
 *          @OA\Property(
 *             property="lugar_nacimiento",
 *             type="string",
 *          ),
 *          @OA\Property(
 *             property="cedula",
 *             type="string",
 *          ),
 *          @OA\Property(
 *             property="grupo_sanguineo",
 *             type="string",
 *          ),
 *          @OA\Property(
 *             property="telefono",
 *             type="string",
 *          ),
 *          @OA\Property(
 *             property="celular",
 *             type="string",
 *          ),
 *          @OA\Property(
 *             property="email",
 *             type="string",
 *          ),
 *          @OA\Property(
 *             property="direccion",
 *             type="string",
 *          ),
 *           @OA\Property(
 *             property="clave_fallas",
 *             type="integer",
 *          ),
 *          @OA\Property(
 *             property="fecha_ingreso",
 *             type="integer",
 *          ),
 *          @OA\Property(
 *             property="genero",
 *             type="string",
 *          ),
 *          @OA\Property(
 *             property="tipo_identificacion_id",
 *             type="integer",
 *          )
 *       ),
 *    ),
 * )
 */